collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

kramdown:
  auto_ids: false
highlighter: rouge
sass:
    style: compressed

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

exclude:
  - build.sh
  - insert_date.sh
  - deploy.sh
  - serve.sh
  - Dockerfile
  - deploy_smashblog
  - LICENSE
  - README.md
  - current_hash.txt
  - refresh_ipns
