#!/bin/bash

# Update repo
echo "---------- Pulling newest version from git repo ----------"
git pull

# Clear _site
echo "---------- Clearing _site ----------"
rm -fr ./_site/*

# Clear staging
echo "---------- Clearing ipfs-staging/blog/ ----------"
rm -fr ~/ipfs-staging/blog/*

# Build new site
echo "---------- Building new site ----------"
./build.sh

# Copy new site to ipfs-staging
echo "---------- Moving site to ipfs staging directory ----------"
cp -r _site/* ~/ipfs-staging/blog/

# Deploy on IPFS
echo "---------- Adding site to IPFS ----------"
HASH=$(docker exec smashserv_ipfs_1 ipfs add -rQ /export/)
echo "Success, new hash: $HASH"

# Write hash to current_hash.txt
echo $HASH > current_hash.txt

# Update IPNS
./refresh_ipns
echo "Done!"
